spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./spring-booklog
logging:
  level:
    com.millky.booklog: TRACE
server:
#  port: 8088
  error:
    whitelabel:
      enabled: false

app:
  key:
    daum: 
    google: 
  impl:
    book: daumLibraryRepository
#    book: googleLibraryRepository
